// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspector.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnverifiedQuestions = `-- name: GetUnverifiedQuestions :many
SELECT q.id,
       q.question_text,
        coalesce(
            json_agg(
                    json_build_object(
                            'letter', c.choice_letter,
                            'text', c.choice_text
                    ) order by c.choice_letter ASC
            )FILTER (where c.id IS NOT NULL),
        '[]'::json
        )::jsonb AS choices
FROM questions q
LEFT JOIN choices c ON q.id = c.question_id
WHERE q.is_verified = false
GROUP BY q.id
ORDER BY q.id ASC
`

type GetUnverifiedQuestionsRow struct {
	ID           int64
	QuestionText string
	Choices      []byte
}

func (q *Queries) GetUnverifiedQuestions(ctx context.Context) ([]GetUnverifiedQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getUnverifiedQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnverifiedQuestionsRow
	for rows.Next() {
		var i GetUnverifiedQuestionsRow
		if err := rows.Scan(&i.ID, &i.QuestionText, &i.Choices); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionVerification = `-- name: UpdateQuestionVerification :exec
UPDATE questions
SET
    correct_choice = $2,
    explanation = $3,
    is_verified = true,
    is_solvable = $4,
    confidence_score = $5
WHERE id = $1
`

type UpdateQuestionVerificationParams struct {
	ID              int64
	CorrectChoice   string
	Explanation     string
	IsSolvable      bool
	ConfidenceScore pgtype.Numeric
}

func (q *Queries) UpdateQuestionVerification(ctx context.Context, arg UpdateQuestionVerificationParams) error {
	_, err := q.db.Exec(ctx, updateQuestionVerification,
		arg.ID,
		arg.CorrectChoice,
		arg.Explanation,
		arg.IsSolvable,
		arg.ConfidenceScore,
	)
	return err
}
