// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Choice struct {
	ID           int64
	QuestionID   int64
	ChoiceText   string
	ChoiceLetter string
}

type DerivedChoice struct {
	ID           int64
	QuestionID   int64
	ChoiceText   string
	ChoiceLetter string
}

type DerivedQuestion struct {
	ID                 int64
	OriginalQuestionID pgtype.Int8
	LevelType          pgtype.Int8
	QuestionText       string
	CorrectChoice      string
	Explanation        string
	CreatedAt          pgtype.Timestamp
}

type InstructionContext struct {
	ID          int64
	SourceID    int64
	ContextText string
}

type LevelType struct {
	ID        int64
	LevelType string
}

type Question struct {
	ID                   int64
	SourceID             int64
	InstructionContextID pgtype.Int8
	SubjectID            int64
	TopicID              pgtype.Int8
	ReferencesDiagram    bool
	QuestionText         string
	CorrectChoice        string
	Explanation          string
	CreatedAt            pgtype.Timestamp
}

type Source struct {
	ID             int64
	FileName       string
	ProcessedStart pgtype.Timestamp
	ProcessedEnd   pgtype.Timestamp
}

type Subject struct {
	ID   int64
	Name string
}

type Topic struct {
	ID        int64
	SubjectID int64
	Name      string
}
