// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: multiplier_1.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChoicesForQuestion = `-- name: GetChoicesForQuestion :many
SELECT choice_letter, choice_text
FROM choices
WHERE question_id = $1
ORDER BY choice_letter
`

type GetChoicesForQuestionRow struct {
	ChoiceLetter string
	ChoiceText   string
}

func (q *Queries) GetChoicesForQuestion(ctx context.Context, questionID int64) ([]GetChoicesForQuestionRow, error) {
	rows, err := q.db.Query(ctx, getChoicesForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChoicesForQuestionRow
	for rows.Next() {
		var i GetChoicesForQuestionRow
		if err := rows.Scan(&i.ChoiceLetter, &i.ChoiceText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingQuestions = `-- name: GetPendingQuestions :many
SELECT q.id, q.question_text
FROM questions q
         LEFT JOIN derived_questions dq ON q.id = dq.original_question_id
WHERE q.subject_id = $1
  AND q.is_derivable = true
  AND dq.id IS NULL
ORDER BY random()
LIMIT 75
`

type GetPendingQuestionsRow struct {
	ID           int64
	QuestionText string
}

func (q *Queries) GetPendingQuestions(ctx context.Context, subjectID int64) ([]GetPendingQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getPendingQuestions, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingQuestionsRow
	for rows.Next() {
		var i GetPendingQuestionsRow
		if err := rows.Scan(&i.ID, &i.QuestionText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDerivedChoice = `-- name: InsertDerivedChoice :exec
INSERT INTO derived_choices (
    question_id, choice_text, choice_letter
) VALUES (
             $1, $2, $3
         )
`

type InsertDerivedChoiceParams struct {
	QuestionID   int64
	ChoiceText   string
	ChoiceLetter string
}

func (q *Queries) InsertDerivedChoice(ctx context.Context, arg InsertDerivedChoiceParams) error {
	_, err := q.db.Exec(ctx, insertDerivedChoice, arg.QuestionID, arg.ChoiceText, arg.ChoiceLetter)
	return err
}

const insertDerivedQuestion = `-- name: InsertDerivedQuestion :one
INSERT INTO derived_questions (
    original_question_id, subject_id, level_type, skills_tested, question_text, correct_choice, explanation
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         ) RETURNING id
`

type InsertDerivedQuestionParams struct {
	OriginalQuestionID pgtype.Int8
	SubjectID          pgtype.Int8
	LevelType          pgtype.Int8
	SkillsTested       pgtype.Text
	QuestionText       string
	CorrectChoice      string
	Explanation        string
}

func (q *Queries) InsertDerivedQuestion(ctx context.Context, arg InsertDerivedQuestionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDerivedQuestion,
		arg.OriginalQuestionID,
		arg.SubjectID,
		arg.LevelType,
		arg.SkillsTested,
		arg.QuestionText,
		arg.CorrectChoice,
		arg.Explanation,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markQuestionUnderivable = `-- name: MarkQuestionUnderivable :exec
UPDATE questions
SET is_derivable = false, derivation_issue = $1
WHERE id = $2
`

type MarkQuestionUnderivableParams struct {
	DerivationIssue pgtype.Text
	ID              int64
}

func (q *Queries) MarkQuestionUnderivable(ctx context.Context, arg MarkQuestionUnderivableParams) error {
	_, err := q.db.Exec(ctx, markQuestionUnderivable, arg.DerivationIssue, arg.ID)
	return err
}
