// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions_choices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearIncompleteQuestions = `-- name: ClearIncompleteQuestions :exec
DELETE FROM questions WHERE source_id = $1
`

func (q *Queries) ClearIncompleteQuestions(ctx context.Context, sourceID int64) error {
	_, err := q.db.Exec(ctx, clearIncompleteQuestions, sourceID)
	return err
}

const createChoice = `-- name: CreateChoice :exec
INSERT INTO choices (
    question_id, choice_text, choice_letter
) VALUES (
             $1, $2, $3
         )
`

type CreateChoiceParams struct {
	QuestionID   int64
	ChoiceText   string
	ChoiceLetter string
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) error {
	_, err := q.db.Exec(ctx, createChoice, arg.QuestionID, arg.ChoiceText, arg.ChoiceLetter)
	return err
}

const createInstructionContext = `-- name: CreateInstructionContext :one
INSERT INTO instruction_contexts (source_id, context_text)
VALUES ($1, $2)
RETURNING id
`

type CreateInstructionContextParams struct {
	SourceID    int64
	ContextText string
}

func (q *Queries) CreateInstructionContext(ctx context.Context, arg CreateInstructionContextParams) (int64, error) {
	row := q.db.QueryRow(ctx, createInstructionContext, arg.SourceID, arg.ContextText)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    source_id, subject_id, topic_id, instruction_context_id, ref_no, references_diagram, question_text, correct_choice
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8
         ) RETURNING id
`

type CreateQuestionParams struct {
	SourceID             int64
	SubjectID            int64
	TopicID              pgtype.Int8
	InstructionContextID pgtype.Int8
	RefNo                string
	ReferencesDiagram    bool
	QuestionText         string
	CorrectChoice        string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.SourceID,
		arg.SubjectID,
		arg.TopicID,
		arg.InstructionContextID,
		arg.RefNo,
		arg.ReferencesDiagram,
		arg.QuestionText,
		arg.CorrectChoice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
