// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects_topics_sources.sql

package db

import (
	"context"
)

const markSourceCompleted = `-- name: MarkSourceCompleted :exec
UPDATE sources SET processed_end = NOW() WHERE id = $1
`

func (q *Queries) MarkSourceCompleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSourceCompleted, id)
	return err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (file_name, file_path, mother_folder, file_size_bytes)
VALUES ($1, $2, $3,$4)
ON CONFLICT (file_name)
    DO UPDATE SET file_path = EXCLUDED.file_path,
                  mother_folder = EXCLUDED.mother_folder,
                  file_size_bytes = EXCLUDED.file_size_bytes
RETURNING id, file_name, file_path, mother_folder, file_size_bytes, processed_start, processed_end
`

type UpsertSourceParams struct {
	FileName      string
	FilePath      string
	MotherFolder  string
	FileSizeBytes int64
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertSource,
		arg.FileName,
		arg.FilePath,
		arg.MotherFolder,
		arg.FileSizeBytes,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.MotherFolder,
		&i.FileSizeBytes,
		&i.ProcessedStart,
		&i.ProcessedEnd,
	)
	return i, err
}

const upsertSubject = `-- name: UpsertSubject :one
INSERT INTO subjects (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
`

func (q *Queries) UpsertSubject(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSubject, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (subject_id, name) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
`

type UpsertTopicParams struct {
	SubjectID int64
	Name      string
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTopic, arg.SubjectID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
