// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects_topics_sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstructionContext = `-- name: CreateInstructionContext :one
INSERT INTO instruction_contexts (source_id, context_text)
VALUES ($1, $2)
RETURNING id
`

type CreateInstructionContextParams struct {
	SourceID    int64
	ContextText string
}

func (q *Queries) CreateInstructionContext(ctx context.Context, arg CreateInstructionContextParams) (int64, error) {
	row := q.db.QueryRow(ctx, createInstructionContext, arg.SourceID, arg.ContextText)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markSourceCompleted = `-- name: MarkSourceCompleted :exec
UPDATE sources SET processed_end = NOW() WHERE id = $1
`

func (q *Queries) MarkSourceCompleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSourceCompleted, id)
	return err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (file_name) VALUES ($1)
ON CONFLICT (file_name) DO UPDATE SET file_name = EXCLUDED.file_name
RETURNING id, processed_end
`

type UpsertSourceRow struct {
	ID           int64
	ProcessedEnd pgtype.Timestamp
}

func (q *Queries) UpsertSource(ctx context.Context, fileName string) (UpsertSourceRow, error) {
	row := q.db.QueryRow(ctx, upsertSource, fileName)
	var i UpsertSourceRow
	err := row.Scan(&i.ID, &i.ProcessedEnd)
	return i, err
}

const upsertSubject = `-- name: UpsertSubject :one
INSERT INTO subjects (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
`

func (q *Queries) UpsertSubject(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSubject, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (subject_id, name) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
`

type UpsertTopicParams struct {
	SubjectID int64
	Name      string
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTopic, arg.SubjectID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
